ecommerceWebSite/accounts/urls.py
from django.conf.urls import url
from .Controllers import views

app_name = 'accounts'

urlpatterns = [
    url(r'signup/', views.signup_view, name='signup'),
    url(r'login/', views.login_view, name="login"),
    url(r'logout/', views.logout_view, name='logout'),
]

ecommerceWebSite/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.apps import apps
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'', include('weShop.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'^oscar/', include(apps.get_app_config('oscar').urls[0])),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceWebSite/weShop/urls.py
from django.conf.urls import url
from .Controllers import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^shop/$', views.shop, name="shop"),
    url(r'^shop-single/(?P<slug>[\d-]+)/$', views.singleProduct, name="singleProduct"),
    url(r'catigory/(?P<slug>[\w-]+)', views.categorys, name="catigory"),
    url(r'^cart/$', views.cart, name="cart"),
    url(r'^addToCart/$', views.addOrUpdate, name='addOrUpdate'),
    url(r'deleteFromCart/(?P<slug>[\w-]+)', views.deleteFromCart, name='deleteFromCart'),
    url(r'checkout/$', views.checkout, name="checkout"),
    url(r'thankyou/$', views.thankyou, name="thankyou"),
    url(r'contact/$', views.contact, name="contact"),
    url(r'^subscribe/$', views.subscribe, name="subscribe"),
]

ecommerceWebSite/weShop/forms.py
from django import forms
from weShop.Models.models import Country, Order

class ossrderForm(forms.Form):
    lName = forms.CharField(max_length=100, label='Last name :', required=True, widget=forms.TextInput(attrs={'class': "form-control"}), error_messages={'required': 'Please enter your name'})
    fName = forms.CharField(max_length=100, label='First name :',  required=True, widget=forms.TextInput(attrs={'class': "form-control"}))
    phone = forms.IntegerField(label='Phone :', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=70, label='Email :', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = forms.ModelChoiceField(required=True, label='Contry :', queryset=Country.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    state = forms.CharField(max_length=40, label='State :', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    codePostal = forms.CharField(max_length=40, label='Code Postal :', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    notes = forms.CharField(max_length=300, label='Note :', widget=forms.Textarea(attrs={"rows": 5, "cols": 30, "class": "form-control", "placeholder": "Write your notes here..."}))




class orderForm(forms.ModelForm):
    class Meta:
        model = Order

        fields = ('lName', 'fName', 'phone', 'email', 'country', 'state', 'codePostal', 'note')

        widgets = {
            'lName': forms.TextInput(attrs={'class': "form-control"}),
            'fName': forms.TextInput(attrs={'class': "form-control"}),
            'phone': forms.TextInput(attrs={'class': "form-control"}),
            'email': forms.TextInput(attrs={'class': "form-control"}),
            'country': forms.Select(attrs={'class': "form-control"}),
            'state': forms.TextInput(attrs={'class': "form-control"}),
            'codePostal': forms.TextInput(attrs={'class': "form-control"}),
            'note': forms.Textarea(attrs={'class': "form-control", "rows": 5, "cols": 30, "placeholder": "Write your notes here..."}),
        }

        labels = {
            'lName': 'last name',
            'fName': 'first name',
            'phone': 'phone',
            'email': 'email',
            'country': 'country',
            'state': 'state',
            'codePostal': 'code Postal',
            'note': 'note',
        }

        error_messages = {
            'lName': {
                'max_length': "This last name is too long.",
                'required': 'Please enter your last name'
            },
            'fName': {
                'max_length': "This first name is too long.",
                'required': 'Please enter your fisrt name'
            },
            'phone': {
                'max_length': "This phone is too long.",
                'required': 'Please enter phone'
            },
            'email': {
                'max_length': "This writer's name is too long.",
                'required': 'Please enter your fisrt name'
            },
            'country': {
                'max_length': "This writer's name is too long.",
                'required': 'Please enter your fisrt name'
            },
            'state': {
                'max_length': "This writer's name is too long.",
                'required': 'Please enter your fisrt name'
            },
            'codePostal': {
                'max_length': "This writer's name is too long.",
                'required': 'Please enter your fisrt name'
            },
            'note': {
                'max_length': "This writer's name is too long.",
                'required': 'Please enter your fisrt name'
            }

        }

ecommerceWebSite/weShop/Controllers/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.http import HttpResponse
from json import dumps
from django.contrib.auth.decorators import login_required
from validate_email import validate_email

from .AbstractController import parmsToMaps
from weShop.forms import orderForm
from weShop.Application.ContactApp import ContactApp
from weShop.Dto.ContactDto import ContactDto
from weShop.Models.models import Subscribe, Product, Category, Service, OrderItem, Order, Country
from django.conf import settings

def index(request):
    context = {}
    catigorys = Category.objects.all() # get all categorys
    services = Service.objects.all() # get all services
    mostSalles = Product.objects.all().order_by('-rank')[:6] # get last 6 items

    context["mostSalles"] = mostSalles
    context["catigorys"] = catigorys
    context["services"] = services
    return render(request, 'index.html', context=context)

def Search(request):
    pass

def shop(request):
    context = {}
    products = Product.objects.all().order_by('-dateDeCreation')
    catigorys = Category.objects.all()
    context["products"] = products
    context["catigorys"] = catigorys
    return render(request, 'shop.html', context=context)

def categorys(request, slug):
    try:
        if request.method == "GET":
            if slug:
                catigorys = Product.objects.filter(category_id=slug)
            else:
                catigorys = Product.objects.all()

            context = {"products": catigorys}
            return render(request, 'shop.html', context=context)
        else:
            return redirect(request, 'index')

    except Exception as err:
        print (err)

def singleProduct(request, slug):
    context = {}
    try:
        # TODO add validation more validation
        mostSalles = Product.objects.all().order_by('-rank')[:6]  # get last 6 items
        product = Product.objects.filter(id=slug)
        context["mostSalles"] = mostSalles
        context['products'] = product
        return render(request, 'shop-single.html', context=context)

    except Exception as e:
        print(e)
        return render(request, 'shop-single.html', context=context)

def cart(request):
    context = {}
    if request.user.is_authenticated:
        carts = OrderItem.objects.filter(user=request.user)
        context["carts"] = carts
        context["total"] = getTotal(carts)
    return render(request, 'cart.html', context=context)

@login_required()
def addOrUpdate(request):
    data = {}

    try:
        if request.method != "POST":
            data['response'] = 'Only POST request supported'
            data['status'] = 405
            return HttpResponse(dumps(data), content_type="application/json")

        slug = request.POST.get('slug')
        quantity = request.POST.get('quantity')

        if slug is None:
            data['response'] = 'all parms is required'
            data['status'] = 400
            return HttpResponse(dumps(data), content_type="application/json")

        checkQuantity = isInit(num=quantity)

        if not checkQuantity:
            data['response'] = 'negative number is not acceptable'
            data['status'] = 400
            return HttpResponse(dumps(data), content_type="application/json")


        item = get_object_or_404(Product, id=slug)

        oldOrders = OrderItem.objects.filter(user=request.user, product=item)

        if len(oldOrders) == 0:
            OrderItem.objects.get_or_create(product=item, user=request.user, quantity=quantity)
            data["response"] = "add to cart"
            data['status'] = 200
            data['incart'] = getItemIncart(request.user)
            request.session['card'] = getItemIncart(request.user) # update user session with the new number of items
            return HttpResponse(dumps(data), content_type="application/json")

        else:
            for oldOrder in oldOrders:
                if quantity is None:
                    oldOrder.quantity += 1
                else:
                    oldOrder.quantity += int(quantity)
                oldOrder.save()
                data["response"] = "Update cart"
                data['status'] = 200
                data['incart'] = getItemIncart(request.user)
                request.session['card'] = getItemIncart(request.user) # update user session with the new number of items
                return HttpResponse(dumps(data), content_type="application/json")

    except (KeyError, Product.DoesNotExist):
        data["response"] = "Something is wrong"
        data['status'] = 500
        return HttpResponse(dumps(data), content_type="application/json")

def getTotal(carts):
    total = 0
    for cart in carts:
        total += cart.get_total_item_price()
    return total

def getItemIncart(user):
    """
    this function used to caclcule number of itme in cart for the current user
    :param user: user who send the request
    :return: total items in cart
    """
    return len(OrderItem.objects.filter(user=user))

@login_required()
def deleteFromCart(request, slug):
    item = get_object_or_404(Product, id=slug)
    OrderItem.objects.filter(product=item).delete()
    request.session['card'] = getItemIncart(request.user)
    return redirect('cart')

@login_required()
def checkout(request):
    context = {}
    try:

        if request.method == 'GET':
            carts = OrderItem.objects.filter(user=request.user)
            countrys = Country.objects.all()

            context["countrys"] = countrys
            context["carts"] = carts
            context["total"] = getTotal(carts)
            form = orderForm()
            context['form'] = form
            return render(request, 'checkout.html', context=context, )

        elif request.method == 'POST':

            data = request.POST
            form = orderForm(data=data)

            if form.is_valid():
                form.save()


                return redirect('thankyou')


            carts = OrderItem.objects.filter(user=request.user)
            countrys = Country.objects.all()

            context["countrys"] = countrys
            context["carts"] = carts
            context["total"] = getTotal(carts)
            context['errors'] = form.errors
            return render(request, 'checkout.html', context=context)

        else:
            pass

    except Exception as e:
        print(e)

def thankyou(request):
    return render(request, 'thankyou.html')

def subscribe(request):
    data = {}
    try:
        if request.method != "POST":
            data['response'] = 'Only POST request supported'
            return HttpResponse(dumps(data), content_type="application/json")

        email = request.POST.get('email')
        if len(email) == 0:
            data['response'] = 'email is required'
            return HttpResponse(dumps(data), content_type="application/json")

        is_valid = validate_email(email)
        if is_valid:
            subscribe = Subscribe()
            subscribe.email = email
            subscribe.save()
            data['response'] = 'Thank you for subscribe'
            return HttpResponse(dumps(data), content_type="application/json")
        else:
            data['response'] = 'Email is invalid'
            return HttpResponse(dumps(data), content_type="application/json")

    except Exception as e:
        print(e)
        data['response'] = "somethings wrrong !"
        return HttpResponse(dumps(data), content_type="application/json")

################### Page Contact ####################################
def contact(request):
    data = {}
    try:
        if request.method == 'GET':
            return render(request, 'contact.html')

        elif request.method == 'POST':
            postParams = ['firstname', 'lastname', 'email', 'subject', 'message'] # expected params
            params = parmsToMaps(request, postParams) # extrcat params form request
            contactDto = ContactDto(params=params) # input dto
            outputDto = ContactApp.add(contactDto) # la couche app
            data['data'] = outputDto # output dto

            return HttpResponse(dumps(data), content_type="application/json")

        else:
            data['error'] = 'Only POST, GET request supported'
            data['statusCode']
            context = {"data": data}
            return render(request, 'contact.html', context=context)

    except Exception as e:
        raise Exception(e)
        data['error'] = "something wrrong please try later !!!"
        return HttpResponse(dumps(data), content_type="application/json")



################### class Utils ######################################
def isInit\
                (num):
    try:
        num = int(num)
        if isinstance(num, int):
            if int(num) > 0:
                return True
        return False
    except ValueError:
        return False

ecommerceWebSite/weShop/templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include 'layout/head.html' %}
  <body>
    {% include 'layout/header.html' %}

    {% block content %}


    {% endblock %}

    {% include 'layout/footer.html' %}

    {% include 'layout/footerscript.html' %}

  </body>
</html>

ecommerceWebSite/weShop/templates/layout/footer.html
{% load static %}
<footer class="site-footer border-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="row">
          <div class="col-md-12">
            <h3 class="footer-heading mb-4">Navigations</h3>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Sell online</a></li>
              <li><a href="#">Features</a></li>
              <li><a href="#">Shopping cart</a></li>
              <li><a href="#">Store builder</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Mobile commerce</a></li>
              <li><a href="#">Dropshipping</a></li>
              <li><a href="#">Website development</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-4">
            <ul class="list-unstyled">
              <li><a href="#">Point of sale</a></li>
              <li><a href="#">Hardware</a></li>
              <li><a href="#">Software</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
        <h3 class="footer-heading mb-4">Promo</h3>
        <a href="#" class="block-6">
          <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded mb-4">
          <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
          <p>Promo from  nuary 15 &mdash; 25, 2019</p>
        </a>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>
          <ul class="list-unstyled">
            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
            <li class="phone"><a href="tel:23923929210">+2 392 3929 210</a></li>
            <li class="email">emailaddress@domain.com</li>
          </ul>
        </div>

        <div class="block-7">
          <form>
            <label for="email_subscribe" class="footer-heading">Subscribe</label>
            <div class="form-group">
              {% csrf_token %}
              <input type="email" class="form-control py-4" id="email_subscribe" placeholder="Email">
              <input type="button" class="btn btn-sm btn-primary" value="Send">
              
            </div>
            <p id="message"></p>
          </form>
        </div>
      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <p>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;</script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>

    </div>
  </div>
</footer>

ecommerceWebSite/weShop/templates/layout/footerscript.html
{% load static %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script>
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>

<script>
    var token = $('meta[name=token]').attr("content");
    $("input[value=Send]").click(function() {
        var email = $("input[type=email]");
        var message =  $("#message");
        $.ajax({
            url: '{% url "subscribe" %}',
            type:'POST',
            headers: {'X-CSRFToken':  token},
            data: {
                'email': email.val(),
            },
            success: function (data) {
                if (data.length != 0){
                    message.text(data.response)
                    email.val('')
                }
            }
        });
    });




    function add(){
        var quantity = $("input[name=quantity]").val();
        var productId = $("input[name=slug]").val();
        addOrUpdateCart(quantity,productId)
    }

    function addOrUpdateCart(quantity,productId){
        var incart = $("#incart")
        $.ajax({
            url: '{% url "addOrUpdate" %}',
            type: 'POST',
            headers: {'X-CSRFToken':  token},
            data: {
                'slug': productId,
                'quantity': quantity,
            },
            success: function (data, textStatus, xhr) {
                if (data.length != 0){
                    var statusCode = data.status;
                   
                    if(statusCode == 405){
                        // methed else POST
                        toastr.warning(data.response);
                    }
                    if(statusCode == 400){
                        // required all params
                        toastr.warning(data.response);
                    }
                    if(statusCode == 200){
                        //success
                        toastr.success(data.response);
                        incart.html(data.incart)
                    }
                    if(statusCode == 500){
                        // failed
                        toastr.warning(data.response);
                    }
                }
            },
            error: function(data, textStatus, xhr){
                toastr.error('failed please try later ');
            }
        });
    }

       
    // submit Contact form 
    $("#contactUs").click(function() {
        var fname = $("#c_fname").val()
        var lname = $("#c_lname").val()
        var email = $("#c_email").val()
        var subject = $("#c_subject").val()
        var message = $("#c_message").val()

        var data = {
            'firstname':fname,
            'lastname':lname,
            'email':email,
            'subject':subject,
            'message':message
        }
        
        $.ajax({
            url: '{% url "contact" %}',
            type:'POST',
            headers: {'X-CSRFToken':  token},
            data: data,
            success: function (data) {
                if (data.length != 0){
                    
                    console.log(data)

                    //var jsonResponse = JSON.parse(data)
                    var statusCode = data.data.statusCode;

                   
                    if(statusCode == 405){
                        toastr.warning(data.data.response);
                    }
                    
                    if(statusCode == 422){
                        toastr.warning(data.data.errors.error);
                    }
                    
                   if(statusCode == 201){
                        //success
                        toastr.success(data.data.response);
                        $("#contactform")[0].reset()
                    }
                }
            }
        });
    });


// $("#contactform")[0].reset()

</script>

ecommerceWebSite/weShop/templates/layout/head.html
{% load static %}
<head>
    <title>Shoppers | Django e-Commerce</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="token" content="{{ csrf_token }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

ecommerceWebSite/weShop/templates/layout/header.html
 <header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div class="container">
          <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
              <form action="" class="site-block-top-search">
                <span class="icon icon-search2"></span>
                <input type="text" class="form-control border-0" placeholder="Search">
              </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="{% url 'index' %}" class="js-logo-clone">Shoppers</a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                  {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout'%}" title="lougout">{{ user.username }}</a></li>
                  {% else %}
                        <li><a href="{% url 'accounts:login'%}" title="login" ><span class="icon icon-person"></span></a></li>
                  {% endif %}

                  <li>

                    <a href="{% url 'cart' %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      {% if request.session.card %}
                      {% comment %} this code here is used to show user the number of item(s) in the cart{% endcomment %}
                        <span class="count" id="incart">{{ request.session.card }}</span>
                      {% else %}
                        <span class="count" id="incart">0</span>
                      {% endif %}
                    </a>
                  </li>
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
          <ul class="site-menu js-clone-nav d-none d-md-block">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'shop' %}">Shop</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>

          </ul>
        </div>
      </nav>
    </header>